services:
  php:
    build:
      context: .
    environment:
      PHP_OPCACHE_ENABLE: "1"
    networks:
      - web-public
    ports:
      - 8080:8080
    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "storage_public:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"
      # - "database_sqlite:/var/www/html/.infrastructure/volume_data/sqlite"
  #    labels:
  #      - "traefik.enable=true"
  #      - "traefik.http.routers.my-php-app.rule=Host(`laravel.callumwk.com`)"
  #      - "traefik.http.routers.my-php-app.entrypoints=websecure"
  #      - "traefik.http.routers.my-php-app.tls=true"
  #      - "traefik.http.routers.my-php-app.tls.certresolver=letsencrypt"
  #      - "traefik.http.services.my-php-app.loadbalancer.server.port=8080"
  #      - "traefik.http.services.my-php-app.loadbalancer.server.scheme=http"
  #      # Health check
  #      - "traefik.http.services.my-php-app.loadbalancer.healthcheck.path=/healthcheck"
  #      - "traefik.http.services.my-php-app.loadbalancer.healthcheck.interval=30s"
  #      - "traefik.http.services.my-php-app.loadbalancer.healthcheck.timeout=5s"
  #      - "traefik.http.services.my-php-app.loadbalancer.healthcheck.scheme=http"

  pgsql:
    image: "postgres:15"
    # ports:
    #   - "${FORWARD_DB_PORT:-5432}:5432"
    environment:
      PGPASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
      - "postgres:/var/lib/postgresql/data"
      # - "./vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql"
    networks:
      - web-public
    healthcheck:
      test:
        - CMD
        - pg_isready
        - "-q"
        - "-d"
        - "${DB_DATABASE}"
        - "-U"
        - "${DB_USERNAME}"
      retries: 3
      timeout: 5s

volumes:
  certificates:
  storage_private:
  storage_public:
  storage_sessions:
  storage_logs:
  database_sqlite:
  postgres:

networks:
  web-public:
