services:
  php:
    build:
      context: .
    environment:
      PHP_OPCACHE_ENABLE: "1"
    networks:
      - web-public
    ports:
      - 8080:8080
    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "storage_public:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"

volumes:
  certificates:
  storage_private:
  storage_public:
  storage_sessions:
  storage_logs:
  database_sqlite:
  postgres:

networks:
  web-public:
