services:
  php:
    build:
      context: .
    environment:
      PHP_OPCACHE_ENABLE: "1"

    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "storage_public:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.<unique_router_name>.rule=Host(`coolify.io`) && PathPrefix(`/`)"
      - traefik.http.routers.<unique_router_name>.entryPoints=http



volumes:
  certificates:
  storage_private:
  storage_public:
  storage_sessions:
  storage_logs:
  database_sqlite:
  postgres:


